### ISSUE TITLE
你怎么确保数据比页面渲染先获取到的

### ISSUE THREAD

**Issue by Luffys6** [CNAD666/flutter_wan#1]
比如首页  数据没请求完成页面渲染了

**Comment by CNAD666** [comment]
通过网络去请求数据，页面肯定在请求到数据前初始化页面。当获取到数据后，将数据存到state里的变量，在通过action里面定义的方法，通知reducer更新页面就行了。我懂你的意思，你应该是用本地json做demo的，实际上你去看看reducer里面的实现，你发现数据改动后，更新页面的操作非常简单

**Comment by xdd666t** [comment]
> 比如首页 数据没请求完成页面渲染了

通过网络去请求数据，页面肯定在请求到数据前初始化页面。当获取到数据后，将数据存到state里的变量，在通过action里面定义的方法，通知reducer更新页面就行了。我懂你的意思，你应该是用本地json做demo的，实际上你去看看reducer里面的实现，你发现数据改动后，更新页面的操作非常简单

**Comment by Luffys6** [comment]
不是这样吧，我现在处理的是，在页面判断数据没获取到先整页显示loading

**Comment by Luffys6** [comment]
我不是本地的json，我就是网络请求的，reducer里面更新状态的

**Comment by xdd666t** [comment]
> 我不是本地的json，我就是网络请求的，reducer里面更新状态的

没问题啊，开始请求的时候开启loading，数据请求成功后关闭loading，然后在reducer里面更新数据就行了，页面数据会自动刷新的，对了你在reducer里面更新的state里的变量，需要你在view里面使用

**Comment by Luffys6** [comment]
> > 我不是本地的json，我就是网络请求的，reducer里面更新状态的
> 
> 没问题啊，开始请求的时候开启loading，数据请求成功后关闭loading，然后在reducer里面更新数据就行了，页面数据会自动刷新的，对了你在reducer里面更新的state里的变量，需要你在view里面使用

嗯  这我明白，我看你写的没加Loading啊，你看看你首页数据，你加下我759902931

**Comment by xdd666t** [comment]
> > > 我不是本地的json，我就是网络请求的，reducer里面更新状态的
> > 
> > 
> > 没问题啊，开始请求的时候开启loading，数据请求成功后关闭loading，然后在reducer里面更新数据就行了，页面数据会自动刷新的，对了你在reducer里面更新的state里的变量，需要你在view里面使用
> 
> 嗯 这我明白，我看你写的没加Loading啊，你看看你首页数据，你加下我759902931

首页我用了这个flutter_easyrefresh下拉刷新 上拉加载的库，没用loading布局。。。。
